### ISSUE TITLE
Are copyright holders correct inside wcs-manifest.json?

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-routeplanner#10]

**Comment by niettadesantis** [comment]
I replaced NOI with IDM.
What I actually not know is, if we have to mention STA (as it's already inserted in the file) and eventually also here.com...?
Do we have to mention all the owners of the api's that are in use in a web component, @sseppi is this something we could discuss with Carlo Piana?

**Comment by Piiit** [comment]
@sseppi @niettadesantis 

I think the copyright holders are those who paid for the code or gave the order to write the code, not companies that provide data through their APIs. So I think, here.com is not meant to be a copyright holder, but STA could be if it was a project with IDM and STA together...?

However, Carlo Piana can maybe shine in on these questions? Is that OK for you, @kappapiana?

**Comment by kappapiana** [comment]
> @sseppi @niettadesantis
> 
> I think the copyright holders are those who paid for the code or gave the order to write the code, not companies that provide data through their APIs. So I think, here.com is not meant to be a copyright holder, but STA could be if it was a project with IDM and STA together...?
> 
> However, Carlo Piana can maybe shine in on these questions? Is that OK for you, @kappapiana?

Not sure I fully understand the question and the factual implications thereof.

**Comment by ohnewein** [comment]
Hi @kappapiana ,

as you know we have a web component store in which web components get published. Every single web component can specify in a manifest file, who the authors of the web component are.

IDM contracted a company to develop a web component:

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/b199dbd5-508c-4de2-b06c-401ff6151ad0 (You have to toggle "Disable car routing, ..." to see anything in the preview) 

In the description in the header you can see the label: Copyright holder And here we do not know whom to add. I suppose only IDM, because they contracted the company to create the web component in their name.

But the company uses different APIs to retrieve data, not only Open Data Hub APIs. For example they use an API provided by STA AG <https://www.sta.bz.it> to do routing calculations and use the maps provided by HERE. 

The question is, should STA, HERE, etc. also be mentioned. I assume not, and if they have, not as Copyright holder.

Maybe HERE has some license conditions where they impose to be mentioned in the map itself like OSM does. But I assume they are not Copyright holders of the web component itself.

Correct?

**Comment by kappapiana** [comment]
Thanks for the explanation, now everything is clearer.

I agree. My opinion is that only the copyright holders of the code inside the repository must be acknowledged. Since this was contracted to an external company, I am pretty sure the copyright has been assigned to IDM, which is the copyright holder (or NOI? I have not seen the arrangements for the spin-off). 

The application consumes the API of third parties, but these third parties have no business with the application itself. They are copyright holder (in principle) of the accessed content  and in this fashion they should be acknowledged.  You are right, I know for sure OSM has a requirement on mention them in the map, I suppose the same goes for HERE and it is safe assume it.

In general, the software that interacts with API is not a derivative of the API themselves (this is quite relatively sure in Europe, under challenge in US, but that's another story). Therefore, even that bit should be attributed to IDM, unless the actual software is provided directly by the API provider.

Please note that in general "authors" should refer to individual persons, not companies, by their name or nickname, to comply with "moral rights" (assuming they exist for software) unless attribution to a company is dictated by an upstream license.

**Comment by ohnewein** [comment]
> My opinion is that only the copyright holders of the code inside the repository must be acknowledged. Since this was contracted to an external company, I am pretty sure the copyright has been assigned to IDM, which is the copyright holder (or NOI? I have not seen the arrangements for the spin-off).

In this case the web component has been developed by IDM. IDM has contracted the company. Therefore I understand from your feedback the field "Copyright holder:" has to be set to "IDM Südtirol - Alto Adige"

> Please note that in general "authors" should refer to individual persons, not companies, by their name or nickname, to comply with "moral rights" (assuming they exist for software) unless attribution to a company is dictated by an upstream license.

That means the field "Author:" should not include the company, but the single developers/employees of the company? Maybe something like "Mario Rossi, Belka"?

**Comment by kappapiana** [comment]
> > My opinion is that only the copyright holders of the code inside the repository must be acknowledged. Since this was contracted to an external company, I am pretty sure the copyright has been assigned to IDM, which is the copyright holder (or NOI? I have not seen the arrangements for the spin-off).
> 
> In this case the web component has been developed by IDM. IDM has contracted the company. Therefore I understand from your feedback the field "Copyright holder:" has to be set to "IDM Südtirol - Alto Adige"
>

Correct. Unless the copyright has been passed through when the two entities parted (I understand the contract was performed when they were one)
 
> > Please note that in general "authors" should refer to individual persons, not companies, by their name or nickname, to comply with "moral rights" (assuming they exist for software) unless attribution to a company is dictated by an upstream license.
> 
> That means the field "Author:" should not include the company, but the single developers/employees of the company? Maybe something like "Mario Rossi, Belka"?

No. If a company wants to put themselves in the file as authors, as a way to claim authorship and to preserve the copyright notice, there is nothing against it. However, this does not mean that moral rights are complied with, as they are granted only to individual.

Therefore: if there is an entry by a company or other legal person, the entry must be dealt with under licensing considerations alone. If it is a natural person, their name must be preserved (if the contribution is above a threshold to be per se protected, not just a quick fix like fixing missing quotes) because it is an issue of moral rights (assuming they exist).

For the employing company, a good practice under moral right would be to anyway put the names of their individual employees as authors.

For the project, there is **no requirement** to **actively seek** for authors' names. The authorship is not waivable. But if the author does not claim authorship, that's fine too. It's an obligation not to suppress, that's it.

**Comment by ohnewein** [comment]
Thank you Carlo for your clarification.
Therefore, in this specific case, I would go for the following values:

```
Author: Belka
Copyright holder: IDM Südtirol - Alto Adige
```

**Comment by kappapiana** [comment]
Seems reasonable.

**Comment by niettadesantis** [comment]
Thank you all!
